print("i live in the city named georgia")
print("today in georgia is bad weather")
print("i selected a another book")
print("i rearranged a tv")
print("i wrote a parentheses incorrectly  ")
print("i have a two variety tv")
print("i lost my phone")
print("i tell my mom to make me a tee")
print("me and my cousin have similiar phones")
print("i have explicit body")